# Generated by Django 5.2.1 on 2025-05-22 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pullrequest_pr_github_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='langgraph_thread_id',
        ),
        migrations.RemoveField(
            model_name='webhookeventlog',
            name='processed_entity_id',
        ),
        migrations.AddField(
            model_name='review',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='last_comment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='thread_id',
            field=models.CharField(default='', help_text='LangGraph thread ID', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='thread_type',
            field=models.CharField(default='main', help_text='Type of thread (main, feedback, followup, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='thread',
            name='title',
            field=models.CharField(blank=True, help_text='Optional thread title or topic', max_length=255, null=True),
        ),
        migrations.AddField(
