# Generated by Django 5.2.1 on 2025-05-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_thread_langgraph_thread_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookeventlog',
            name='event_id',
            field=models.CharField(blank=True, help_text='GitHub event ID (X-GitHub-Delivery)', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='webhookeventlog',
            name='headers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
