# Generated by Django 5.2.1 on 2025-05-23 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_webhookeventlog_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookeventlog',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='core.repository'),
        ),
    ]
