# Generated by Django 5.2.1 on 2025-05-24 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_repository_to_webhook_event_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
